### ISSUE TITLE
Builder with default values

### ISSUE THREAD

**Issue by kleewho** [artem-zinnatullin/AutoJackson#6]
Here's the thing. I'd like to use Builder to support default values for some of the fields. It would look like this:

``` java
@AutoValue
@JsonDeserialize(builder = AutoValue_Tweet.Builder.class)
public abstract class Tweet {

    @NotNull
    @JsonCreator
    public static Builder builder() {
        return new AutoValue_Tweet.Builder().content("Immutability not for everybody!");
    }

    @NotNull
    @JsonProperty("author")
    public abstract String author();

    @NotNull
    @JsonProperty("content")
    public abstract String content();

    @AutoValue.Builder
    public static abstract class Builder {

        @NotNull
        @JsonProperty("author")
        public abstract Builder author(@NotNull String author);

        @NotNull
        @JsonProperty("content")
        public abstract Builder content(@NotNull String content);

        @NotNull
        public abstract Tweet build();
    }
}
```

which according to this page http://wiki.fasterxml.com/JacksonFeatureBuilderPattern should work. Any ideas what I'm doing wrong? Basically @JsonCreator is ignored. With auto value I can't use builder and static factory method (to build in code using builder and jackson would have to deal with factory method) cause c-tor is private.

**Comment by artem-zinnatullin** [comment]
The reason why Jackson ignores `@JsonCreator` is because you've set `@JsonDeserialize(builder = AutoValue_Tweet.Builder.class)` so Jackson will instantiate builder class via its constructor instead of your method. Also, as far as I know `@JsonCreator` won't work with builders, it's just for creating instance of the class directly.

You can try to specify default value for json deserialization via annotation on the builder class, like `@JsonProperty(defaultValue)`, though [documentation says that databind module won't use it…](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations)

I've faced another issue with AutoValue which may resolve yours if it'll be fixed https://github.com/google/auto/issues/287#issuecomment-168046996

Another approach — not to have default values and use `null`, yeah.

Unfortunately, I don't see other solutions at the moment (except writing custom deserialization), so I'm closing this. Please comment if you find better solution!

**Comment by kleewho** [comment]
@artem-zinnatullin but please, check the link http://wiki.fasterxml.com/JacksonFeatureBuilderPattern:

``` java
@JsonDeserialize(builder=ValueBuilder.class)
public class Value {
  private final int x, y;
  protected Value(int x, int y) {
    this.x = x;
    this.y = y;
  }
}
public class ValueBuilder {
  private int x, y;

  // can use @JsonCreator to use non-default ctor, inject values etc
  public ValueBuilder() { }

  // if name is "withXxx", works as is: otherwise use @JsonProperty("x") or @JsonSetter("x")!
  public ValueBuilder withX(int x) {
    this.x = x;
    return this; // or, construct new instance, return that
  }
  public ValueBuilder withY(int y) {
    this.y = y;
    return this;
  }

  public Value build() {
    return new Value(x, y);
  }
}
```

This is the example from link, and there's `@JsonDeserializer` and commented out (but presented as optional) `@JsonCreator`. 

I didn't find better solution yet. Fortunately I was able to ditch builder completely and just use static factory, but it's not always an option so it would be nice to know.

**Comment by artem-zinnatullin** [comment]
I've checked your link…

Can you try this one (I'm currently using Gson at work and don't have time to play with Jackson):

``` java
@AutoValue
@JsonDeserialize(builder = AutoValue_Tweet.Builder.class)
public abstract class Tweet {

    @NotNull
    @JsonCreator
    public static Builder builder() {
        return new AutoValue_Tweet.Builder().content("Immutability not for everybody!");
    }

    @NotNull
    @JsonProperty("author")
    public abstract String author();

    @NotNull
    @JsonProperty("content")
    public abstract String content();
}

    @AutoValue.Builder
    public static abstract class Builder {

        @NotNull
        @JsonProperty("author")
        public abstract Builder author(@NotNull String author);

        @NotNull
        @JsonProperty("content")
        public abstract Builder content(@NotNull String content);

        @NotNull
        public abstract Tweet build();

        @JsonCreator // Here is the trick.
        public Builder builderForJson() {
            return Tweet.builder();
        }
    }
```

I think it ignores your `@JsonCreator` because you've put it into entity class, not inside builder class!

// Notice `builderForJson()` inside builder, hope it'll help!

**Comment by kleewho** [comment]
Unfortunately it's not working
